import type { OperatorOption } from "./types";

export const DEFAULT_OPERATORS: OperatorOption[] = [
    {
        label: "equals",
        value: "eq",
        aliases: ["equals", "equal", "equal to", "is equal to", "eq", "=", "==", "is"],
    },
    {
        label: "not equals",
        value: "ne",
        aliases: [
            "not equals",
            "not equal",
            "not equal to",
            "is not equal to",
            "ne",
            "!=",
            "is not",
            "isn't",
            "isnt",
            "doesn't equal",
            "does not equal",
        ],
    },
    {
        label: "greater than",
        value: "gt",
        aliases: [
            "greater than",
            "gt",
            ">",
            "more than",
            "bigger than",
            "above",
            "exceeds",
            "higher than",
        ],
    },
    {
        label: "greater than or equal to",
        value: "gte",
        aliases: [
            "greater than or equal to",
            "greater than or equal",
            "gte",
            ">=",
            "at least",
            "no less than",
            "not less than",
            "not smaller than",
            "not below",
            "not under",
        ],
    },
    {
        label: "less than",
        value: "lt",
        aliases: [
            "less than",
            "lt",
            "<",
            "fewer than",
            "smaller than",
            "below",
            "under",
            "lower than",
        ],
    },
    {
        label: "less than or equal to",
        value: "lte",
        aliases: [
            "less than or equal to",
            "less than or equal",
            "lte",
            "<=",
            "at most",
            "no more than",
            "not greater than",
            "not bigger than",
            "not above",
            "not more than",
        ],
    },
    {
        label: "contains",
        value: "contains",
        aliases: ["contains", "includes", "has", "not missing"],
    },
];
